<?php
namespace Tarefa\Persistencia;

class TarefaDao extends AbstractDao
{
    public function __construct()
    {
        parent::__construct('Tarefa\Entidade\Tarefa');
    }

    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }
}